openapi: 3.0.3
info:
  title: Walk Suitability API
  description: |
    散歩適性指数API - 天気と空気質データを統合し、ユーザーに科学的な散歩提案を提供

    本サービスは以下の2つの公開APIを呼び出します：
    - OpenWeatherMap API (天気データ)
    - World Air Quality Index API (空気質データ)

    これらのデータを融合して総合的な「散歩適性指数」(0-100点)を計算します。

  version: 1.0.0
  contact:
    name: API Support
    email: support@walksuitability.com

servers:
  - url: http://localhost:5000
    description: ローカル開発サーバー
  - url: http://your-production-server.com
    description: 本番サーバー

tags:
  - name: Walk Suitability
    description: 散歩適性関連インターフェース
  - name: Weather
    description: 天気データインターフェース
  - name: Air Quality
    description: 空気質データインターフェース
  - name: System
    description: システムインターフェース

paths:
  /:
    get:
      tags:
        - System
      summary: API情報
      description: APIの基本情報と利用可能なエンドポイントを取得
      responses:
        '200':
          description: API情報を正常に返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    example: Walk Suitability API
                  version:
                    type: string
                    example: 1.0.0
                  description:
                    type: string
                  endpoints:
                    type: object

  /health:
    get:
      tags:
        - System
      summary: ヘルスチェック
      description: APIサービスが正常に動作しているかを確認
      responses:
        '200':
          description: サービスは正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time

  /api/walk-suitability:
    get:
      tags:
        - Walk Suitability
      summary: 散歩適性指数を取得
      description: |
        指定都市の天気と空気質データに基づいて、散歩適性指数を計算して返します。

        評価基準：
        - 80-100点：散歩に非常に適している
        - 60-79点：散歩に適している
        - 40-59点：普通
        - 0-39点：散歩に不適

        計算要素：
        - 気温 (重み: 25%)
        - 天気状況 (重み: 25%)
        - 空気質 (重み: 30%)
        - 湿度 (重み: 10%)
        - 風速 (重み: 10%)
      parameters:
        - name: city
          in: query
          description: 都市名(英語)
          required: false
          schema:
            type: string
            default: Tokyo
            example: Tokyo
      responses:
        '200':
          description: 散歩適性データを正常に返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  city:
                    type: string
                    example: Tokyo
                  timestamp:
                    type: string
                    format: date-time
                  suitability:
                    type: object
                    properties:
                      score:
                        type: number
                        format: float
                        description: 散歩適性指数 (0-100)
                        example: 85.5
                      level:
                        type: string
                        description: 適性レベル
                        enum: [非常に適している, 適している, 普通, 不適]
                        example: 非常に適している
                      recommendation:
                        type: string
                        description: 散歩提案
                        example: 今は散歩に最適な時間です！
                      reasons:
                        type: array
                        items:
                          type: string
                        description: 評価理由の説明
                        example: ["天気と空気質が両方とも良好です"]
                      details:
                        type: object
                        properties:
                          temperature_score:
                            type: number
                            example: 100.0
                          weather_score:
                            type: number
                            example: 100.0
                          humidity_score:
                            type: number
                            example: 80.0
                          wind_score:
                            type: number
                            example: 100.0
                          aqi_score:
                            type: number
                            example: 80.0
                  weather:
                    $ref: '#/components/schemas/WeatherData'
                  air_quality:
                    $ref: '#/components/schemas/AirQualityData'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/weather:
    get:
      tags:
        - Weather
      summary: 天気データを取得
      description: OpenWeatherMap APIから指定都市の天気情報を取得
      parameters:
        - name: city
          in: query
          description: 都市名(英語)
          required: false
          schema:
            type: string
            default: Tokyo
            example: Tokyo
      responses:
        '200':
          description: 天気データを正常に返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  city:
                    type: string
                    example: Tokyo
                  timestamp:
                    type: string
                    format: date-time
                  data:
                    $ref: '#/components/schemas/WeatherData'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/air-quality:
    get:
      tags:
        - Air Quality
      summary: 空気質データを取得
      description: World Air Quality Index APIから指定都市の空気質情報を取得
      parameters:
        - name: city
          in: query
          description: 都市名(英語)
          required: false
          schema:
            type: string
            default: Tokyo
            example: Tokyo
      responses:
        '200':
          description: 空気質データを正常に返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  city:
                    type: string
                    example: Tokyo
                  timestamp:
                    type: string
                    format: date-time
                  data:
                    $ref: '#/components/schemas/AirQualityData'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    WeatherData:
      type: object
      description: 天気データオブジェクト
      properties:
        temperature:
          type: number
          format: float
          description: 気温(摂氏)
          example: 22.5
        feels_like:
          type: number
          format: float
          description: 体感気温(摂氏)
          example: 21.8
        humidity:
          type: integer
          description: 湿度(パーセント)
          example: 65
        weather:
          type: string
          description: 天気状況
          example: Clear
        weather_description:
          type: string
          description: 天気の詳細説明
          example: clear sky
        wind_speed:
          type: number
          format: float
          description: 風速(メートル/秒)
          example: 3.5
        clouds:
          type: integer
          description: 雲量(パーセント)
          example: 20

    AirQualityData:
      type: object
      description: 空気質データオブジェクト
      properties:
        aqi:
          type: integer
          description: 空気質指数 (AQI)
          example: 45
        pm25:
          type: number
          format: float
          description: PM2.5濃度
          nullable: true
          example: 12.5
        pm10:
          type: number
          format: float
          description: PM10濃度
          nullable: true
          example: 25.3
        o3:
          type: number
          format: float
          description: オゾン濃度
          nullable: true
          example: 30.2
        no2:
          type: number
          format: float
          description: 二酸化窒素濃度
          nullable: true
          example: 15.8

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: エラーメッセージ
          example: 天気データ取得失敗
